### ISSUE TITLE
the libuv doesn't support cross compile?

### ISSUE THREAD

**Issue by Kevin0626** [Azure/iot-edge#234]
Hi, I failed to build edison platform with script "/azure-iot-gateway-sdk/tools/inteledison_c.sh". Can anyone confirm it is still working?

Then I tried  the command "tools/build.sh --config Debug --toolchain-file [my toolchain file]. It gave following message:

checking whether we are cross compiling... configure: error: in `/home/xin/repos/open/azure-iot-gateway-sdk/build_libuv/libuv':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.

Then I see the script "build_libuv.sh" has following statement:
./configure --prefix=$build_root/dist/ CFLAGS='-fPIC' CXXFLAGS='-fPIC'

It seems not use the cross compile parmaters.

**Comment by zafields** [comment]
Yes, you are correct. Our cross-compiled environments do not currently support native remote modules. This is a scenario we want to support in the future, but don't have the bandwidth currently.

The workaround is to `--disable-native-remote-modules`. However, if you have the time, we would appreciate a PR to enable cross-compiling of libuv (and subsequently, the remote modules feature).

**Comment by aribeironovaes** [comment]
Closing this issue since we have a work around (According to Zack message) and we don't plan to add this in v1. PR still welcome.

**Comment by kiranpradeep** [comment]
This is disappointing. That is not a work around. That is like telling out-of-proc modules are not supported any more. Does this mean that #326, #320 and #444 will also be closed soon with out fixes? Are out-of-proc modules no more supported?

I will use v2 where ever possible. But not every one in the world can run docker or pull down 200 MB docker containers. v1 in-proc modules had the disadvantage that a crash in any module bring down the entire gateway process. Only hope was out-of-proc modules leaving a debugging channel back into gateway.

**Comment by aribeironovaes** [comment]
Hi @kiranpradeep , 
I'm sorry this is disappointing. When Zak mentioned Workaround, it's a workaround to get gateway v1 to crosscompiling, not to make libuv to Crosscompile. 

The think is that this is one of the issues that, since we are open source, a PR that fixes the issue would be very welcome, but we won't be spending cycles focusing on fixing this on V1. 

I agree that sometimes, if you are using V1 and you hit limitation on the devices, it's won't be possible to move to v2, but we hope that the fact this project is Open Source, it will keep the possibility open for this to still be used. 

Totally agree with you as well with Pros and Cons regarding in-proc and out-of-proc. 

Let us know if you would like to contribute to fix this issue. 
Letting this issue open when we don't plan to work on it would be misleading and make people to wait for a resolution. 

I don't have details about the issues you mention above, it will be a case by case. I can tell you that we don have a meeting to triage older issues as well to make sure our list of list are in sync with our priorities. 

Thanks, 

Angelo Ribeiro.

**Comment by kiranpradeep** [comment]
@aribeironovaes I could be wrong here. Just letting you know my personal opinion.

As per the last update on 11-15-2017[[1](https://github.com/Azure/iot-edge/blob/e43bd8d0d3bf90a3e206dc6dc741c9fea566cd27/v1/README.md#11152017)], v1 modules are expected to be supported and bugs can continue to be filed in the issues section of this repo. Till now, there is no official communication that v1 out-of-proc modules are not supported anymore. Once that communication is made, it is perfectly fine for the project maintainer to close issues as they feel fit. libuv cross compile is a crucial part of out-of-proc modules, and it doesn't make sense to say (or give an impression like)  _we support out-of-proc v1 modules_  and then close this issue. 

IMHO, a project being open source shouldn't be the consideration for closing issues.
