### ISSUE TITLE
BLE Module posting messages to Broker with "content" not in JSON format

### ISSUE THREAD

**Issue by tonymarte** [Azure/iot-edge#249]
I managed to install the SDK on Raspberry Pi3, and run the BLE sample app (using a real SensorTag).
I receive messages in the IoT Hub (monitored them from the Device Explorer). However, when I try to send the data from IoT Hub to Stream Analytics I get "data formatting error". 

After some troubleshooting I found out that the BLE Module posts messages to the Broker with "content" not in JSON format, and stream analytics only interprets json (or csv) messages.
Moreover, the value of the Temperature Characteristic, when passed to the IoT Hub, are not in a readable form. The Manufacturer data and other strings characteristics were received fine. Can this be related to the BUFFER_u_char function?

I tried to modify the ble.c in the BLE Module adding/modifying:

char msgText[128];
sprintf_s(msgText, sizeof(msgText), "{\"my_value\": \"%s\"}", BUFFER_u_char(data));
message_config.source = (const unsigned char*)msgText;

This worked fine when the values of the BLE characteristics were strings (eg. BLE Manufacturer). However, when the values of the characteristic were integers (eg Temperature (as in the example)), the values sent to the IoT Hub were not usable. I guess the values get messed up at the output of the BUFFER_u_char function.

Any idea how to solve? 

Thank you very much

**Comment by tonymarte** [comment]
UPDATE : 
apparently even the "content" from sensor.js in the nodejs_simple_sample sends data not in the json format, and hence is not readable once reaches the IoT Hub and not detected in Stream Analytics

**Comment by darobs** [comment]
Hello @tonymarte  

It's intentional that the BLE module produces a non-JSON output. The format of the data is binary - the buffer output straight from the Bluetooth command. There's two reasons for this. 1) the sample is showing the "protocol encapsulation" use case - the gateway is making no assumptions about the content of the messages coming from the Bluetooth device, and we're assuming the upstream ingestion understands the data, and 2) the contents of the JSON would be dictated by the Stream Analytics query, so we chose not to force our assumptions about the name-value pairs in the BLE module output.

The actual content of the temperature data is [this](http://processors.wiki.ti.com/index.php/CC2650_SensorTag_User's_Guide#Data).

My recommendation would be to create a BLE->JSON interpretation module  and place it in the pipeline between the BLE module and the IoTHub module.  This module would read the contents of the BLE message and reinterpret it to JSON.  You could also do this in the cloud, but you'd save money on cloud compute time if you do it as a gateway module.

While we don't have a module that does this, I can point you to the "ble_printer" module used in the sample.  It does read the BLE message content and converts it into a displayable format (for some characteristic UUIDs) .  This is it: [ble_printer.c](https://github.com/Azure/azure-iot-gateway-sdk/blob/master/samples/ble_gateway/ble_printer/src/ble_printer.c)

The displayable format could be used as the value for the JSON name-value pair.

I hope that helps.  Please let me know if there's anything else I can help you with this.
Thanks,

**Comment by tonymarte** [comment]
Hello, thank you very much for the reply.
I understand, thanks for the explanation, I will try to do that in future. 

Nevertheless, for straight/out-of-the-box usage of the Gateway SDK, it would be nice if such a module was included in the future releases of the SDK. (That would simply speed up the adoption of the SDK)

**Comment by tees54** [comment]
Can you give me more hints, where i could easily implement the console output
of the temperature, to the iot hub sent message? I could not trace the date flow.
Or is it possible to send the message to the iot hub in the ble_printer.c?

**Comment by darobs** [comment]
This is a very quick, uncompiled, untested conversion of the ble_printer module into a BLE to JSON converter module:
[ble_printer.c](https://github.com/darobs/azure-iot-gateway-sdk/blob/ble_convert_to_json/samples/ble_gateway/ble_printer/src/ble_printer.c)

**Comment by aribeironovaes** [comment]
Closed due to inactivity and according to last message from David.
