### ISSUE TITLE
Environment variables need to be set for Windows too

### ISSUE THREAD

**Issue by andyw248** [Azure/iot-edge#263]
I think this: "Copy and paste the export message that shows up on screen to set the NODE_INCLUDE and NODE_LIB environment variables" is required for Windows as well, not just for Linux.

**Comment by darobs** [comment]
You are correct, NODE_INCLUDE and NODE_LIB  are required environment variables in Windows as well.

**Comment by zafields** [comment]
We were able to set these previously using the `.cmd` script, so the instructions were not necessary. However, it looks like `build_nodejs.cmd` received a powershell infused upgrade since then.

@avranju Did this behavior change with the introduction of the powershell script?

**Comment by avranju** [comment]
Yes, the behavior has indeed changed with the PS version of the Node.js build script on Windows. This was done when we stopped using our own fork of Node.js and consequently gained the ability to use any arbitrary version of Node.js via the `--node-version` argument to the build script (`build_nodejs.cmd`). So now the behavior of both the Windows and Linux scripts are identical in that they simply print instructions at the end of the build instead of also setting the environment variables as well.
