### ISSUE TITLE
Support for Raspian

### ISSUE THREAD

**Issue by melzoghbi** [Azure/iot-edge#268]
Hi,

Is there a plan to support Raspian OS in IoT edge? Raspbian is a widely supported OS for wide range of IoT boards which makes it straight forward to integrate with IoT edge.

**Comment by melzoghbi** [comment]
edit

**Comment by damonbarry** [comment]
In the past we've demonstrated that we can build/run our SDK on Raspberry Pi. But in order to officially support it we need to be able to run it as part of our continuous integration, we need to be able to cross-compile for RPi, and we've had some trouble getting that worked out.

We haven't been able to make time recently to investigate this again, but we hope to do it in the near future. However, if someone else wants to take a look we'd love the help!

**Comment by faister** [comment]
Hi @darobs, did you just check in a fix to enables IoT Edge to run on Raspberry Pi?
Thus far, I'd been able to cross-compile for linux-arm for dotnetcore_binding and the sample dotnetcore modules using .NET Core 2 Preview 2 SDK. This is because the .NET Core 2 runtime is now available on arm32. See https://github.com/dotnet/core/blob/master/samples/RaspberryPiInstructions.md 

However, where I'm stuck is when I try to run the dotnet_core_managed_gateway sample, in which the gw console cannot load the dotnetcore loader. It requires libdotnetcore.so. Unfortunately this is only available in the NuGet packages for microsoft.azure.devices.gateway.native.debian.x64 and microsoft.azure.devices.gateway.native.ubuntu.x64. 

Is there anyway I could also cross-compile the packages for Linux-arm? I'm willing to help, but need some guidance.

Thanks

**Comment by aribeironovaes** [comment]
HI @faister, 

Our Nuget packages were created and are maintained by this git repo: 
https://github.com/Azure-Samples/iot-edge-samples

Can you open an issue there asking for them to add the arm version? 

Meanwhile what you can do is to add a script to copy the binary you need (like the libdotnetcore.so). 

Thanks!

Angelo Ribeiro.

**Comment by damonbarry** [comment]
Available in the 2017-08-21 release.

**Comment by malichishti** [comment]
@damonbarry how can i get this release? #406
