### ISSUE TITLE
iothub module and serializer library in azure-iot-sdk-c

### ISSUE THREAD

**Issue by kiranpradeep** [Azure/iot-edge#402]
iot-edge has a module named iothub[(1)][1] which handles all communications including message reception from Azure IoTHub. Azure-iot-sdk-c  provides [serializer][4] library which makes it easy to work with device twins and direct method invocations. But it appears if lib user uses iothub module as it is now, he cannot take advantage of the serializer functions(direct methods/twins) in a clean way[(2)][2].

My assumption is device twins/direct method code for each protocol ingestion module is to part of the acquisition module itself and not part of iothub module. For e.g if a Modbus module is to stop collecting data on a direct method invocation( e.g. `WITH_ACTION(StopModbus`)), the `DECLARE_MODEL` should be written inside Modbus module[(3)][3] and not inside iothub module. With the way, iothub module is currently written, we cannot do this. 

Is the above assumption wrong? Should we put in all device twin/direct method code into iothub and make it into a big monolith?  What is the alternative? Serializer is a helpful library. But iothub module is restrictive.

[1]: https://github.com/Azure/iot-edge/blob/master/modules/iothub/devdoc/iothub.md 
[2]: https://github.com/Azure/azure-iot-sdk-c/blob/c05ea05925dcec29bf28f04eec899b400fa23df0/serializer/samples/devicetwin_simplesample/devicetwin_simplesample.c#L146
[3]: https://github.com/Azure/iot-gateway-modbus
[4]: https://github.com/Azure/azure-iot-sdk-c#serializer

**Comment by damonbarry** [comment]
You're correct. Device-specific code would need to go into the module that knows about that device; the iothub module needs to remain generalized. In order to get twin/methods working end-to-end inside IoT Edge v1, you'd need to define a set of generic messages that match twin/method operations. Your protocol ingestion module could receive the generic messages intended for a specific device.

I haven't looked closely at the newer features in the serializer, but the problem I see with using them in the gateway is that serialization and client operations are tightly coupled. And in gateway scenarios, as you described, we need to be able to decouple them.

**Comment by damonbarry** [comment]
As described above, I don't think we can integrate with the twins/methods feature of the serializer, since it requires tight coupling between the device and the client, and the gateway breaks those two roles apart. BTW, originally the serializer was written in such a way that it was NOT tightly coupled to the client, and that was intentional. I'm not sure why the coupling was introduced later for twins/methods--maybe that was the only reasonable option.

Closing...
