### ISSUE TITLE
Provide documentation for jenkins/raspberrypi_c.sh

### ISSUE THREAD

**Issue by malichishti** [Azure/iot-edge#415]
Hi,

IS there any documentation on how to use [jenkins/raspberrypi_c.sh](https://github.com/Azure/iot-edge/blob/master/v1/jenkins/raspberrypi_c.sh) ?

Regards,
Ali

**Comment by darobs** [comment]
Hello @malichishti,

Everything in the "jenkins" directory is used for our Jenkins server builds and is part of the V1 check-in gate.  It's used to cross-compile the code for the RPi, which is why I'm assuming you're interested...

If you want an easy way out, we have a [docker image](https://hub.docker.com/r/aziotbld/raspberrypi-c/) set up to do Raspberry Pi cross-compiling. (I recently used it to cross-compile other libraries as well.) `raspberrypi_c.sh` is designed to be used with this image.  No guarantees this will be there forever, but this image is how we currently launch the Jenkins build. 

Essentially, the requirements to run the script are: 
[Setting up a Linux development environment](https://github.com/Azure/iot-edge/blob/master/v1/doc/devbox_setup.md#set-up-a-linux-development-environment).
The [Pi tool chain](https://github.com/raspberrypi/tools) installed in `${HOME}/RPiTools/tools`.
The native libraries (content of /lib/arm-linux-gnueabihf) installed in  `${HOME}/RPiTools/arm-linux-gnueabihf`.

**Comment by malichishti** [comment]
Thank you
