### ISSUE TITLE
[V2][Preview] MODULE_API deprecated?

### ISSUE THREAD

**Issue by kiranpradeep** [Azure/iot-edge#448]
In the samples provided in modules-preview branch of azure-iot-sdk-c, MODULE_API (_Publish, _Receive, _Create, _Start, _ParseConfiguration etc) is no more used. Is MODULE_API no more used in V2?

If yes, it appears like filter and sender examples in modules-preview branch(azure-iot-sdk-c) communicates with EdgeHub over TCP(even though filter and sender are processes in a single machine). Is that understanding correct?

**Comment by darobs** [comment]
Hi @kiranpradeep, there's a bit of naming overlap here.

The "modules-preview" branch of the C SDK is intending to show the creation of modules on the IoTHub, where modules are sub-devices to an IoTHub device. The purpose of modules on the IoTHub is to give distinct data, operation and behavior to components of an IoTHub device.  The "modules" concept on IoTHub (and the C SDK) is usable independent of an Edge Device.

That said, Azure IoTHub Edge V2 is utilizing the IoTHub modules concept to manage modules in V2.  When a module is configured to run on the Edge, it will create a module identity for it. Then the V2 modules will communicate to the Edge device via the IoTHub SDK (C, C# or otherwise) over TCP.  A modules written in C to communicate to the Edge will need to use this "modules-preview" branch to get the module support needed, until this branch is merged into master.

So, yes, we are moving away from the MODULES_API and using the C SDK for V2.

**Comment by kiranpradeep** [comment]
That helps in better understanding of SDK. I wasn't aware that modules could be used indepedent of EdgeHub. But, here I am slightly confused in the used terms like IoTHub device vs Edge Device. Can you please confirm if the below understanding is correct?

IoTHub Device - A device added under Azure IoTHub portal
EdgeDevice - EdgeHub(azure-iot-edge-runtime-ctl) installed on gateway by python-pip

There is no sample in modules-preview branch to indicate the "modules" concept could be used independent of EdgeDevice/EdgeHub. All samples require a connection string provided by environment variable so that "modules" can connect to EdgeHub. Where will that connection string come from when modules are used independent of EdgeHub?  Can you please give a pointer on how to run modules independent of EdgeDevice/EdgeHub?

The original query was regarding the choice of TCP to communicate between modules in a single computer. At a first glance, from a narrow perspective, that doesn't appear the best way for inter-module communication in a single computer. This query is not of much importance or an issue, but I still likes to know why TCP was favoured over inter-process communication methods.

**Comment by darobs** [comment]
It would probably help if I used consistent naming myself. :)

On the IoTHub service, one may create a device, that device can either be created as an Edge device (Edge capabilities turned on) or not.  You may create a module on any kind of device. The distinction is that an Edge device creates 2 system modules - `$edgeAgent` and `$edgeHub` - and receives deployments.

One of the key features of V2 is that the concepts of V1 are now also mapped to the service.  An Edge device is both a physical device running the Azure IoT Edge software, but it is also represented by a device on the IoTHub service.  Likewise, modules are discrete software bundles installed on the Edge device, but are also represented on the IoTHub with unique identification and configuration.

While the modules concept is supported for Edge devices, modules for non-edge devices isn't fully integrated into the service yet (i.e. there is not yet Portal support). The module REST APIs have been implemented on the service for Edge public preview, but there is no documentation yet for how to manage modules other than through a Edge device. 


Why TCP? Because we chose to use the Azure IoT SDKs are our basis of module communications.
- We wanted to use the same SDK for modules and devices.  Ideally, the same code could be used for both, the only difference being the connection string.
- The SDKs have identity, authorization and secure communications already in place and is stable.

Also because we chose containers as the module delivery mechanism, the common accepted standard for communicating from containers is TCP, whether on the same or networked computers.

TCP also keeps the modules independent, and so where the module executes becomes less important - a critical concept when doing test and deployment from the cloud.

**Comment by kiranpradeep** [comment]
@darobs Thanks for the detailed reply. Really helps in better understanding. A query here is that, when a device is created without Edge capabilities (no $edgeHub), then how does modules communicate with each other? Maybe I should wait for the documentation.


Of lesser importance: On an ARM based Linux gateway, I had tried running v1 out-of-proc modules in LXC containers. The containers had a shared ramdisk for the control and message channels. It worked well with out TCP in between.  All the use cases I work are needing the identity translation pattern. I am yet to work on a real-world case which needs the transparent gateway pattern. So from a narrow perspective of a single gateway/computer(identity-translation), TCP even on the loopback interfaces couldn't take any advantage like zero-copy provided by nanomsg. It will also bring in overhead like additional packet headers, packet ordering etc. I am afraid that the solution with TCP for single computer scenario(identity-translation) is not fast as it could be. But neither I have a usecase where in I am limited by TCP. So no complaints.

**Comment by darobs** [comment]
> A query here is that, when a device is created without Edge capabilities (no $edgeHub), then how does modules communicate with each other? 

As I understand it, they wouldn't.  One of the purposes of modules on a non-Edge device is to subdivide a device into distinct submodules where data and control are separated. If you have a device with multiple sensors, you may choose to create each sensor as a module so they have independent configuration and data.  You could then choose to manipulate the data based on the module/sensor, or update the firmware on only one type of sensor in the device. Applications like that, and more.

Thanks for the feedback, I'll make sure our team sees them.
