### ISSUE TITLE
[V2] How to deploy in an offline mode?

### ISSUE THREAD

**Issue by malichishti** [Azure/iot-edge#452]
Hi,

I would like to know if V2 can be deployed in offline mode? What i mean by offline mode is without being connected to Azure IoT Hub. A deployment were i can independently deploy my code modules to the Edge, configure their routing and have them running without ever needing cloud or IoT Hub.

Regards,
Ali

**Comment by PtwHub** [comment]
Thanks Damonbarry. A clear strategy here is crucial since it determines whether designers can use IoT-Edge for On-Premises solutions or not. Hybrid systems often have long off-line periods. Also, there are scenarios where an installation needs to be On-Premises only: a classical installation of the IoT-Edge without a direct cloud connection (as you had in V1 of Edge) as well as its operation without assumption of cloud presence. Can you please tell us what the strategy is here so we can make decisions regarding the usability of IoT-Edge for hybrid designs? Thanks!

**Comment by damonbarry** [comment]
@PtwHub We recognize that use cases for IoT Edge connectivity to the public cloud run the spectrum from always connected to fully isolated.

The strategy for public preview is to have a solution that _must_ connect to Azure in the public cloud, but which can also go offline (for some period of time at least) and continue to function. Specifically, the edge device must (1) connect to IoT Hub to be managed (receive deployments or config updates, and report out its status). It must also (2) connect to IoT Hub to authenticate any devices or modules that connect to it. But if the edge device has received a deployment and authenticated the right modules and devices, then I believe it can remain offline for long periods, assuming the modules and devices keep their connections alive. To be fair, there's currently a bug in this scenario (#467) which is being addressed.

As for changes/updates to that strategy in the future, know that we're looking into whether we want to support the fully isolated (on-prem) scenario, and if so, how. You'll want to keep your eye on the [Azure IoT Edge](https://azure.microsoft.com/en-us/services/iot-edge/) website, and the [Azure IoT blog](https://azure.microsoft.com/en-us/blog/topics/internet-of-things/) for updates like this.

Also, the Azure IoT Edge [feedback portal](https://feedback.azure.com/forums/907045-azure-iot-edge) is a good place to record this feedback--and it looks like you've already done [that](https://feedback.azure.com/forums/907045-azure-iot-edge/suggestions/32994373-make-iot-edge-v2-usable-again-in-products-wh)!
