### ISSUE TITLE
[V2] Strong coupling to IoT-Hub prevents hybrid-OnPrem usage of IoT-Edge?

### ISSUE THREAD

**Issue by PtwHub** [Azure/iot-edge#478]
Hi. In version 1 of Edge, we could use the IoT-Hub module or not simply via configuration of the routes. In our product scenario we must support both OnDemand and OnPrem deployments. To support OnPrem (i.e. connect to an OnPrem .NET-Core App server instead of IoT-Hub) we would have simply configured the V1 Edge route to use a web server module (e.g. kestrel) and OnPrem REST coms instead of the IoT-Hub to Azure. My question: it looks like IoT-Edge V2 is tightly coupled with IoT-Hub and, as such, prevents us from using IoT-Edge as a single source base for both OnDemand and OnPrem deployments. 

Thanks for a clear strategy regarding this so we can determine if IoT-Edge still meets our needs.

**Comment by aribeironovaes** [comment]
Hi @PtwHub , 

If i understand your scenario correctly you want to have a module to be deployed OnPrem (to use REST Coms) so your other modules connects to it instead of Edge Hub. Is it right? 
This is supported today, you can actually do the following: 
1-Develop your modules and deploy to your device (you can actually choose form of deployment), today we have the ability to do that through our portal for deployment or you can use our tools (Like Azure CLI: : https://github.com/Azure/azure-iot-cli-extension
You can actually create your own deployment Json and use it and edge Agent would go and deploy your modules for you. 

So, if you are talking about full OFFLINE capability, where you can deploy our runtime and run it without connecting to Edge Hub, it's on our backlog, so it's definitely an strategy. 

Let us know if this answer your question, 

Thanks, 

Angelo Ribeiro.

**Comment by PtwHub** [comment]
Angelo, thanks for clearing this up. The emphasis on the pure-cloud solution is so omnipresent in the V2 information, that it is hard to determine which parts can still work without a cloud-connection dependency. This looks very promising. We will definitely take a look. Our situation is pretty common, conceptually simple (not necessarily its design): we want single source, we want to offer an OnDemand (cloud-centric) solution but we must also offer a more classic deployment OnPremises where, at most, we connect to the cloud to configure the system and rarely to update it. However, there are even scenarios where no cloud connectivity at all is available at all, never. These must be configured and maintained purely via configuration files like Edge hat in V1. Doable with V2?

**Comment by aribeironovaes** [comment]
It is definitely in our radar and backlog. 

Thanks!

Angelo Ribeiro

**Comment by damonbarry** [comment]
Also addressed in #452. I'll close this issue, especially because we also have an [entry](https://feedback.azure.com/forums/907045-azure-iot-edge/suggestions/32994373-make-iot-edge-v2-usable-again-in-products-wh) in the Azure feedback portal to track it...
