### ISSUE TITLE
[V1] Change of routing mechanism?

### ISSUE THREAD

**Issue by Zuendelmeister** [Azure/iot-edge#500]
Hi all,

I have a question regarding the routing mechanism of Edge_V1. If I configure that module1 sends to module 2 than module2 gets every single message from module1. In Edge_V2 we have the possibility of configuring routes. With this we are able to say module1.output1 sends to module2.input1 but module1.output2 sends to module3.input1. With this it is far easier to declare complex module messaging.
Is this planed for Edge_V1? In my opinion this would be a great enhancement.

Thanks and best regards,
Zuendelmeister

**Comment by chipalost** [comment]
Hi Zuendelmeister, we are not planning on back porting that feature to V1. Input/outputs and filters on routes are provided by using Edge Hub as the message broker between modules. Those features would have to be pulled out an rationalized with the V1 nanomsg based broker.

V1 will continue to be supported; however you should expect most new features to be added to V2. We've tried very hard to make the migration process from V1 to V2 as seamless as possible so that all customers can move forward as IoT Edge evolves. As part of that effort we published an article about how you can migrate V1 modules to V2. You can find that article at https://github.com/Azure/iot-edge/blob/master/v1/doc/migration_from_v1_to_v2.md.

**Comment by Zuendelmeister** [comment]
Hi @chipalost 
thanks for the link. My intention is not to migrate to V2, but to use both. I think with V1 and V2 together there are allot more possibilities than to use just one of them. Still, it's good to hear that the support for V1 will continue.
Is there a feed or anything for news about updates for V1 and V2 to keep track?

Best regards,
Zuendelmeister

**Comment by damonbarry** [comment]
For v1, check the [Releases](https://github.com/Azure/iot-edge/releases) page. Since v2 is still in preview, you can get updates via the [Azure IoT blog](https://azure.microsoft.com/en-us/blog/topics/internet-of-things/).
