### ISSUE TITLE
[V1] Access broker information

### ISSUE THREAD

**Issue by Zuendelmeister** [Azure/iot-edge#518]
Hi all,

if I send allot of messages very fast from module to module it seems like some messages are dropped. Is that possible? If yes, is it possible to get broker information like message count in the queue and count of dropped messages?

Best regards,
Zuendelmeister

**Comment by Zuendelmeister** [comment]
I'd like to add that it would be great for the modules to know if all the modules are running (so after gateway successfully created from JSON). With this it is much saver than before.

**Comment by damonbarry** [comment]
Yes, it is possible to drop messages if you allow the sender to outrun the receiver--find out more about this [here](https://github.com/nanomsg/nanomsg/issues/390#issuecomment-98404170).

There are no metrics built into the v1 broker. We're working on that for v2.

**Comment by srberard** [comment]
For v2, is the plan to continue with NanoMsg and a custom broker or to leverage something like Mosquitto?

**Comment by damonbarry** [comment]
@srberard No v2 uses a scaled-down version of our IoT Hub service that runs locally on the edge device--we call it Edge Hub, and it's part of the IoT Edge runtime. So you use our Azure IoT SDK to send and receive messages in your module, rather than a custom broker API. We currently support connections to Edge Hub via MQTT but we'll also add AMQP. You can set up QOS to get "at least once" semantics so you don't drop messages. Note that we store messages in the filesystem until they can be delivered, so if a destination module is down for a long period of time, or you're trying to send events to IoT Hub and you're offline for a long time, you have to worry about filling up the disk. In public preview we provide only limited strategies for managing the queues of messages (messages can be removed after a certain period of time, but not when the queue reaches a certain size in bytes). We'll provide more control in coming releases.

**Comment by srberard** [comment]
@damonbarry Thanks, appreciate the detail.
