### ISSUE TITLE
Problem with OneDrive caused by old libuv version

### ISSUE THREAD

**Issue by ciberado** [Azure/iot-edge#575]
I'm using OneDrive as a sync mechanism between the two laptops I use to work (it complements git). Unfortunately looks like it is not possible to create V1 modules inside a OD folder (at least with nodejs) because the version of libuv used doesn't handle correctly windows reparse points used by OneDrive.

Looks like this problem is solved in newer versions of the library.

```
ERROR: Error: EINVAL: invalid argument, lstat 'C:\Users\Javi\OneDrive'
Error: Time:Mon Apr  9 12:44:44 2018 File:C:\agent\_work\2\s\iot-edge\bindings\nodejs\src\nodejs.cpp Func:?NODEJS_Create@@YAPEAXPEAUBROKER_HANDLE_DATA_TAG@@PEBX@Z Line:135 Node process failed to start
Error: Time:Mon Apr  9 12:44:44 2018 File:C:\agent\_work\2\s\iot-edge\bindings\nodejs\src\nodejs.cpp Func:?on_module_start@@YAXPEAUNODEJS_MODULE_HANDLE_DATA@@@Z Line:943 Expected registerModule to return 'true' but it returned 'false'Error: Time:Mon Apr  9 12:44:44 2018 File:C:\agent\_work\2\s\iot-edge\core\src\gateway_internal.c Func:gateway_addmodule_internal Line:446 Module_Create failed.

Error: Time:Mon Apr  9 12:44:44 2018 File:C:\agent\_work\2\s\iot-edge\core\src\gateway_createfromjson.c Func:Gateway_CreateFromJson Line:78 Failed to create gateway using lower level library.
Error: Time:Mon Apr  9 12:44:44 2018 File:C:\agent\_work\2\s\src\gw\src\main.c Func:main Line:50 An error occurred while creating the gateway.

Gateway child process exited with code = 1
```

**Comment by mrohera** [comment]
Thank you for your comment. Do you have specifics of what libuv library version addresses this problem?

**Comment by ciberado** [comment]
Thanks for the quick answer!

Sorry, not my area of expertise... but the error should be easy to reproduce: just clone the repo inside a OneDrive folder and try to run it.

```
https://github.com/Azure-Samples/iot-edge-samples
cd iot-edge-samples\js\simple
npm run local
```

**Comment by damonbarry** [comment]
To address this, our node binding will need to be upgraded to run against a newer version of Node.js. This is probably not a trivial effort, because V8 tends to make breaking changes from one version to the next. We already have issue #387 to track this work.

If you want to write a Node.js module that runs in IoT Edge v1, another option would be to write the module as a Node.js app which runs out of process. This would use whatever version of Node.js is installed on your system. See the [sample](https://github.com/Azure/iot-edge/tree/master/v1/samples/nodejs_remote_sample) for more information.

I'll close this since we already have an issue filed to track this work.
