### ISSUE TITLE
Desired properties and CSX edge function apps

### ISSUE THREAD

**Issue by davebanthorpe** [Azure/iot-edge#614]
HI - can anyone advise how to handle desired properties changes on an edge function module written in CSX?  If the module is written in C# you a have callback handler for the properties changed applied to the hub client object. But in CSX you just have a Run method that is called whenever a message is received - but this does not seem to be triggered on a properties change so I assume is only listening to hub messages from downstream/upstream devices accoriding to the routing.

CSX function example here: https://docs.microsoft.com/en-us/azure/iot-edge/tutorial-deploy-function

**Comment by aribeironovaes** [comment]
Hi @davebanthorpe , 

You are right. Currently our Function binding just support Messages, not Twin. So, we are not exposing changes on Module Twin Property on function. 
I'm sure it is on our backlog for us to work on it, however it's not in yet. 
In order to get a good sense of interest on this feature, one thing you can do is to search of there is an entry here for this feature: https://feedback.azure.com/forums/321918-azure-iot

If you don't find, you can add one and our PMs will prioritize accordingly. 

Another good thing is that, very soon, we will open source our bind, so you will even be able to add yourself and contribute back. 

Stay tuned and thanks for using our Edge and giving us feedback, 

Angelo Ribeiro.

**Comment by davebanthorpe** [comment]
Thanks for the update - will make sure the feature is reqeusted
