### ISSUE TITLE
Default cmake project generation shouldn't require elevated privileges

### ISSUE THREAD

**Issue by dcristoloveanu** [Azure/iot-edge#70]
If cmake is ran in a VS x86 command prompt without admin rights there is an error that I did not figure out yet how to bypass.

D:\azure-iot-gateway-sdk\cmake>cmake ..
-- Building for: Visual Studio 12 2013
-- CMake Install Prefix is C:/Program Files (x86)/azure_iot_gateway_sdk-1.0.0/
-- AIG architecture: x86
-- ctest not found...
-- Building ctest...
-- Configuring done
-- Generating done
-- Build files have been written to: D:/azure-iot-gateway-sdk/deps/ctest/build
-- Installing ctest. Please wait...
CMake Error at gatewayFunctions.cmake:117 (message):
  Error installing ctest: 1
Call Stack (most recent call first):
  dependencies-test.cmake:9 (findAndInstall)
  CMakeLists.txt:156 (include)

-- Configuring incomplete, errors occurred!
See also "D:/azure-iot-gateway-sdk/cmake/CMakeFiles/CMakeOutput.log".
See also "D:/azure-iot-gateway-sdk/cmake/CMakeFiles/CMakeError.log".

**Comment by andrew-buckley** [comment]
Hi @dcristoloveanu, CMake will attempt to install all dependencies that don't already exist on your machine. It will attempt to install those dependencies in the default system location (which requires admin privileges) unless you tell it to do otherwise. You may either set the CMake variable `dependency_install_prefix` to a directory which doesn't require admin privileges to write to, or you may run the build script which will install dependencies to the directory `install_deps` within your repo.

**Comment by aribeironovaes** [comment]
Closing per Andrew's comment. Let me know if you want to reactivate it.
