### ISSUE TITLE
Allow comments in Json

### ISSUE THREAD

**Issue by stefangordon** [Azure/iot-edge#88]
Just an idea - I can imagine everyone has mixed feelings on it.

If we change the called to `json_parse_file()` at https://github.com/Azure/azure-iot-gateway-sdk/blob/master/core/src/gateway_createfromjson.c#L57

to `json_parse_file_with_comments()` parson will let us use c style comments (/**/ and //) in our JSON.  Which of course is not in the spec, but is extremely nice during development when you are slotting different modules in and out of the config.

It would also allow for more in-line documentation in the sample configs.

I have been using the gateway with this change and it is rather nice.  

Feel free to close or I can send a PR for the one line change if people want to add it.

**Comment by damonbarry** [comment]
I ran across the parson function `json_parse_file_with_comments()` just yesterday for the first time, and had the same thought. I think we could add a cmake option `allow_comments_in_json` (OFF by default) that would cause our code to use `json_parse_file_with_comments()` instead of `json_parse_file()`.

Sounds like a great PR!

**Comment by myagley** [comment]
Thanks for the feature request. However, at this time, we are not planning to take on this work. We would be happy to take a pull request. Thanks!
